package utils;

import com.google.gson.JsonObject;

import java.util.UUID;

public class XmppHelper {

    private XmppHelper() {
    }

    /**
     * Creates a JSON encoded GCM message.
     *
     * @param to             RegistrationId of the target device (Required).
     * @param messageId      Unique messageId for which CCS sends an
     *                       "ack/nack" (Required).
     * @param payload        Message content intended for the application. (Optional).
     * @param collapseKey    GCM collapse_key parameter (Optional).
     * @param timeToLive     GCM time_to_live parameter (Optional).
     * @param delayWhileIdle GCM delay_while_idle parameter (Optional).
     * @return JSON encoded GCM message.
     */
    public static String createJsonMessage(String to, String messageId,
                                           JsonObject payload, String collapseKey, Long timeToLive,
                                           Boolean delayWhileIdle) {

        JsonObject message = new JsonObject();

        message.addProperty("to", to);
        if (collapseKey != null) {
            message.addProperty("collapse_key", collapseKey);
        }
        if (timeToLive != null) {
            message.addProperty("time_to_live", timeToLive);
        }
        if (delayWhileIdle != null && delayWhileIdle) {
            message.addProperty("delay_while_idle", true);
        }
        message.addProperty("message_id", messageId);
        message.add("data", payload);

        return message.toString();
    }

    /**
     * Creates a JSON encoded ACK message for an upstream message received
     * from an application.
     *
     * @param to        RegistrationId of the device who sent the upstream message.
     * @param messageId messageId of the upstream message to be acknowledged to CCS.
     * @return JSON encoded ack.
     */
    public static String createJsonAck(String to, String messageId) {
        JsonObject message = new JsonObject();
        message.addProperty("message_type", "ack");
        message.addProperty("to", to);
        message.addProperty("message_id", messageId);

        return message.toString();
    }

    /**
     * Returns a random message id to uniquely identify a message.
     * <p>
     * <p>Note: This is generated by a pseudo random number generator for
     * illustration purpose, and is not guaranteed to be unique.
     */
    public static String nextMessageId() {
        return "rd-" + UUID.randomUUID().toString() + "-rc";
    }
}
